### ISSUE TITLE
Increase TTL to support offline dev scenarios

### ISSUE THREAD

**Issue by joshka** [localtest-dot-me/localtest-dot-me.github.com#2]
https://news.ycombinator.com/item?id=7627675
"This is pretty useful! Maybe a noob question but how does this work offline / slow internet connections? I'm coding on the train pretty frequently and I hate waiting for urls to resolve... "

A possible solution would be to increase the TTL to 1 day (?) to fix this scenario.

**Comment by markstos** [comment]
For any subdomains of localtest.me you use frequently, add them `/etc/hosts`. No network dependency, high performance, and the IP address they resolve to is not changing. 

The problem with setting the TTL to 1 day is that your system may not have run a DNS lookup on the domain before you get on the train, so it doesn't matter if the result will be cached for 1 day if you can't look up the value to cache the result in the first place.

**Comment by joshka** [comment]
Wow - necro-thread :) No real buy-in for this issue for me. You're right on the `/etc/hosts` approach, so no problem with closing this out as a WONTFIX.

**Comment by tathamoddie** [comment]
I've just updated the TTL to 3 days.
