### ISSUE TITLE
Why didn't I think of this!

### ISSUE THREAD

**Issue by LordRampantHump** [localtest-dot-me/localtest-dot-me.github.com#4]
This idea is absolutely amazing, as the readme says, so simple yet so dam powerful! However i want to take it to the next level. 

Today while trying to work out how i could test my site on my mobile devices i thought about ways i might overcome the lack of hosts file on a mobile phone. On top of that, localhost is not sufficient as I would need to connect to my host pcs IPv4 address. 

In the end i just pointed a spare domain I have to my ipv4 address and boom! I can now test my domain on any device.

**Comment by vatsalyagoel** [comment]
have a look at [ngrok](https://ngrok.io/) for those sort of testing scenarios.
