### ISSUE TITLE
Support IPv6

### ISSUE THREAD

**Issue by FranklinYu** [localtest-dot-me/localtest-dot-me.github.com#5]
Please support IPv6. If I understand correctly, you can simply add a AAAA record pointing `*.localtest.me` to `::1`.

**Comment by tathamoddie** [comment]
The current zone file includes `ipv6.localtest.me` and `*.ipv6.localtest.me`

```
*.localtest.me. 259200 IN A 127.0.0.1
localtest.me. 259200 IN A 127.0.0.1
ipv6.localtest.me. 3600 IN AAAA ::1
*.ipv6.localtest.me. 3600 IN AAAA ::1
```

This was added years ago though, and is a pretty old approach. The world is very much dual-stack now.

I think it should be safe to add `AAAA ::1` to the main responses by now.

Or, more specifically, I'm sure it'll break something in an automated test harness somewhere, but it's 2022 and IPv6 is well and truly a thing now so it's about time it breaks.

As of Windows 11, `ping localhost` now resolves to `::1` as well.

**Comment by tathamoddie** [comment]
Done.

This is the updated zone file:

```
*.localtest.me. 259200 IN A 127.0.0.1
*.localtest.me. 259200 IN AAAA ::1
localtest.me. 259200 IN A 127.0.0.1
localtest.me. 259200 IN AAAA ::1
ipv6.localtest.me. 259200 IN AAAA ::1
*.ipv6.localtest.me. 259200 IN AAAA ::1
readme.localtest.me. 3600 IN CNAME localtest-dot-me.github.com.
```
