### ISSUE TITLE
Is it still working ?

### ISSUE THREAD

**Issue by omasseau** [localtest-dot-me/localtest-dot-me.github.com#8]
Doing a nslookup of localtest.me does not return anything

**Comment by AndreVirtimo** [comment]
Try different DNS server. I also have a problem with my Fritzbox router, where I have set also these two DNS server.

```
[7:48:05] ➜  ~ nslookup localtest.me 1.1.1.1
Server:		1.1.1.1
Address:	1.1.1.1#53

Non-authoritative answer:
Name:	localtest.me
Address: 127.0.0.1

[7:48:12] ➜  ~ nslookup localtest.me 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
Name:	localtest.me
Address: 127.0.0.1

[7:48:18] ➜  ~ nslookup localtest.me
Server:		192.168.178.1
Address:	192.168.178.1#53

Non-authoritative answer:
*** Can't find localtest.me: No answer
```

**Comment by AndreVirtimo** [comment]
For Fritzbox router I found the issue. There is a protection for DNS entries which points to internal devices.

You can add an exception for "localhost.me" under
Netzwerk - Netzwerkeinstellungen - DNS-Rebind-Schutz
I this in english it should be:
network - network configuration - DNS rebind protection

**Comment by AaronSadlerUK** [comment]
Another vote for @AndreVirtimo answer, this resolved it for me

**Comment by omasseau** [comment]
> For Fritzbox router I found the issue. There is a protection for DNS entries which points to internal devices.
> 
> You can add an exception for "localhost.me" under Netzwerk - Netzwerkeinstellungen - DNS-Rebind-Schutz I this in english it should be: network - network configuration - DNS rebind protection

Thanks indeed the problem was my Fritzbox router.
Hooray. Lost so much time with this :)
